port:  5000
markdown: kramdown
name: "My Reps"
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find state legislators"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyByBYfQTDqG6GSYj3bBSjzmY5Zca32pvRk
